### ISSUE TITLE
Generate working URLs as output

### ISSUE THREAD

**Issue by mgax** [hoover/reup#8]
So now the app displays the checksums it finds in its database. Users can copy/paste them into hoover search and find their documents. But we can already provide a clickable URL to the search results page. Let's define an environment variable, e.g. `REUP_MD5_URL="https://hoover.example.org/?q=md5%3A{md5}"`, which can be used in Python code like `url = REUP_MD5_URL.format(md5=value)`. Also another variable `REUP_SHA1_URL`.

**Comment by alexneamtu** [comment]
@mgax Please have a look at https://github.com/hoover/reup/pulls
